version: '3.7'
services:
    # The Go App
    api:
        build:
            context: .
            dockerfile: ./docker/golang/Dockerfile
        container_name: api
        depends_on:
            - 'postgres'
        environment:
            - PORT=8000
        ports:
            - '8000:8000'
        volumes:
            - './api:/opt/api:cached'
    # PostgreSQL
    postgres:
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile 
        container_name: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=fire
            - TZ=Asia/Tokyo
            - LANG=ja_JP.UTF-8
        ports:
            - '5432:5432'
        volumes:
            - './postgres/data:/var/lib/postgresql/data'