CREATE TABLE users (
  id serial PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(355) NOT NULL,
  email VARCHAR(355) UNIQUE NOT NULL,
  created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)